languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "Max Qian's blog"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
description = "关于计算机领域的杂谈"
# copyright = "Copy, _right?_ :thinking_face:"
copyright = "©2024 Max Qian"

[params.author]
name = "Max Qian"
image = "img/author.jpg"
headline = "路虽远，行则将至"

links = [
  { github = "https://github.com/AstroAir" },
  { envelope-solid = "mailto:qwdmax@qq.com" },
  { zhihu = "https://www.zhihu.com/people/qrming" },
]

