languageCode = "en"
languageName = "English"
weight = 1

title = "MaxQian's Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "Miscellaneous Talks about the Computer Field"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Max Qian"
  image = "img/author.jpg"
  headline = "Although the road is far, the journey is approaching"
  links = [
    { github = "https://github.com/AstroAir" },
    { envelope-solid = "mailto:qwdmax@qq.com" },
    { zhihu = "https://www.zhihu.com/people/qrming" },
  ]